title: Amy Tam # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  C.S. Major at Harvey Mudd College
  Software Engineer & Product Designer
  <br><br>
  Hi! I'm Amy, a computer science major at Harvey Mudd College. 
  I enjoy creating and designing experiences that make lives 
  easier and more enjoyable.
  <br><br>
  I fell in love with the intersect between software and design. 
  As a software engineer, I have the ability to build paths to 
  pave the way to a better future. As a designer, I have the 
  opportunity to make journeys smoother and visually appealing.
  <br><br>
  <a href="https://www.linkedin.com/in/amytam01/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
