title: Amy Tam # your name (or website title) here
logo: "/images/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  C.S. Major at Harvey Mudd College
  Software Engineer & Product Designer
  <br><br>
  Hi! I'm Amy, a computer science major at Harvey Mudd College. 
  I enjoy creating and designing experiences that make lives 
  easier and more enjoyable.
  
  <a href="https://www.linkedin.com/in/amytam01/">View My LinkedIn Profile</a> 
  <a href="https://docs.google.com/document/d/1BxHZBSJ-UlpVITdHcqwXFX7xfpH_hVB5QN9m7mhPilA/edit?usp=sharing">View My SWE Resume</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
